### ISSUE TITLE
No cache found

### ISSUE THREAD

**Issue by pizzafox** [pizzafox/netlify-cache-nextjs#95]
> We are currently getting this issue under the same circumstances -- we have the package included in our netlify.toml and that is all we have done. We are using `next-on-netlify` to enable serverless functions if that is relevant. Is there any further discovery as to what resolved this?

---
 
> I did not previously have the plugin installed in Netlify itself, just declared in our repo -- is this necessary? this was not clear from the docs.
> 
> However, I am still receiving the message.
 
---

> and one last thing -- similarly, locally it appears to work (on second build)

> ```
> $ netlify build --context=deploy-preview
> ...
> ┌────────────────────────────────────────────────────────┐
> │ 1. onPreBuild command from netlify-plugin-cache-nextjs │
> └────────────────────────────────────────────────────────┘
> 
> .next/cache exists on disk
> Restored the cached .next folder at the location `.next/cache`
> 
> (netlify-plugin-cache-nextjs onPreBuild completed in 323ms)
> ```

_Originally posted by @pmourer in https://github.com/pizzafox/netlify-cache-nextjs/issues/80#issuecomment-686785436_

**Comment by pmourer** [comment]
Let me know if there's anything else I can try or provide as far as info, the repo is private unfortunately.

**Comment by pizzafox** [comment]
The previous issue was never really properly resolved, it stopped occurring after a few days without change. The plugin hasn't changed since then, and since it works locally and on other Netlify builds I'm (still) inclined to believe this is an upstream issue with Netlify's library or infrastructure.

That makes me think this is a Netlify side issue. Try sending them [a support request](https://www.netlify.com/support/) and feel free to include me in the ticket. My email is jonah@jonah.pw.

**Comment by pmourer** [comment]
I sent a support request, however I didn't see any sort of "ticket"... maybe once they respond there will be one opened? If so, i will include you once I am able.

**Comment by pizzafox** [comment]
IIRC their Zendesk will email you shortly after filling out there form.

**Comment by pmourer** [comment]
They replied and have said they do not provide support for third party plugins and they included a link to this topic as a likely place to find a solution.

**Comment by pmourer** [comment]
Now that I'm taking a look, they do state this pretty clearly in the plugin docs as well: https://docs.netlify.com/configure-builds/build-plugins/#get-help

> Netlify Build Plugins are created by developers at Netlify and in the community. **If you need help with a plugin, contact the plugin author by submitting an issue on the plugin repository.** For plugins in the Netlify UI, you can find a link to the plugin issues under the Options menu for the plugin listing. If a plugin author doesn't respond to an issue within a week, you can request deactivation of the plugin from the Netlify UI.

**Comment by pmourer** [comment]
So my best guess is that when included in the netlify.toml, for some reason this is installing version 1.4.0 on our instances, perhaps something with Netlify needs to be updated for the latest release? a bump in their system? Or perhaps this truly does mean it is something on there end for some reason? I am not familiar with the plugin/netlify relationship and who handles what.

here's the log (note the output that seems to resemble a previous version):
```
4:14:40 PM: ❯ Loading plugins
4:14:40 PM:    - netlify-plugin-cache-nextjs@1.4.0 from netlify.toml
4:14:42 PM: ​
4:14:42 PM: ┌────────────────────────────────────────────────────────┐
4:14:42 PM: │ 1. onPreBuild command from netlify-plugin-cache-nextjs │
4:14:42 PM: └────────────────────────────────────────────────────────┘
4:14:42 PM: ​
4:14:42 PM: No cache found for the .next folder at the location `.next/cache`
4:14:42 PM: ​
4:14:42 PM: (netlify-plugin-cache-nextjs onPreBuild completed in 251ms)
```

**Comment by pmourer** [comment]
Here's what is in our netlify.toml 

```
[[plugins]]
package = "netlify-plugin-cache-nextjs"
```

**Comment by pizzafox** [comment]
Hmm, I'll do a bit of testing with my repo and see what I find.

**Comment by moop-moop** [comment]
We are only using the Netlify installed configuration-less setup (not in netlify.toml) and are not seeing this problem.
Last build (node 12.16.2):
`9:45:30 AM: ❯ Config file
9:45:30 AM:   /opt/build/repo/netlify.toml
9:45:30 AM: ​
9:45:30 AM: ❯ Context
9:45:30 AM:   production
9:45:30 AM: ​
9:45:30 AM: ❯ Loading plugins
9:45:30 AM:    - netlify-plugin-cache-nextjs@1.4.0 from Netlify app
9:45:30 AM:    - @netlify/plugin-sitemap@0.3.4 from Netlify app
9:45:30 AM:    - netlify-plugin-contextual-env@0.3.0 from Netlify app
9:45:30 AM:    - @uwhealth/netlify-plugin-jest@1.0.0 from netlify.toml and package.json
9:45:32 AM: ​
9:45:32 AM: ┌────────────────────────────────────────────────────────┐
9:45:32 AM: │ 1. onPreBuild command from netlify-plugin-cache-nextjs │
9:45:32 AM: └────────────────────────────────────────────────────────┘
9:45:32 AM: ​
9:45:32 AM: Restored the cached .next folder at the location `.next/cache`
9:45:32 AM: ​
9:45:32 AM: (netlify-plugin-cache-nextjs onPreBuild completed in 412ms)`

**Comment by pmourer** [comment]
Thanks @moop-moop we will see what happens if we go to installing on netlify.com only

**Comment by pizzafox** [comment]
Yeah uhhhh my personal website is also using 1.4.0 (which is outdated, 1.5.0 was released a month ago), will investigate further.

**Comment by moop-moop** [comment]
> 
> 
> We are not using `next-on-netlify` in this repo, but we are in another, so I will check that one too.
Build with `next-on-netlify` library also ok. Also using netlify.com installed plugin.
```console
9:22:54 AM: ❯ Version
9:22:54 AM:   @netlify/build 3.3.5
9:22:54 AM: ​
9:22:54 AM: ❯ Flags
9:22:54 AM:   deployId: *
9:22:54 AM:   mode: buildbot
9:22:54 AM: ​
9:22:54 AM: ❯ Current directory
9:22:54 AM:   /opt/build/repo
9:22:54 AM: ​
9:22:54 AM: ❯ Config file
9:22:54 AM:   /opt/build/repo/netlify.toml
9:22:54 AM: ​
9:22:54 AM: ❯ Context
9:22:54 AM:   production
9:22:54 AM: ​
9:22:54 AM: ❯ Loading plugins
9:22:54 AM:    - @netlify/plugin-sitemap@0.3.4 from Netlify app
9:22:54 AM:    - netlify-plugin-contextual-env@0.3.0 from Netlify app
9:22:54 AM:    - netlify-plugin-cache-nextjs@1.5.0 from netlify.toml and package.json
9:22:55 AM: ​
9:22:55 AM: ┌──────────────────────────────────────────────────────────┐
9:22:55 AM: │ 1. onPreBuild command from netlify-plugin-contextual-env │
9:22:55 AM: └──────────────────────────────────────────────────────────┘
9:22:55 AM: ​
9:22:56 AM: Exporting URL=https://***.
9:22:56 AM: Exporting PATHS_FILE_NAME=paths.js.
9:22:56 AM: Replaced 2 ENVs
9:22:56 AM: ​
9:22:56 AM: (netlify-plugin-contextual-env onPreBuild completed in 6ms)
9:22:56 AM: ​
9:22:56 AM: ┌────────────────────────────────────────────────────────┐
9:22:56 AM: │ 2. onPreBuild command from netlify-plugin-cache-nextjs │
9:22:56 AM: └────────────────────────────────────────────────────────┘
9:22:56 AM: ​
9:22:56 AM: .next/cache exists on disk
9:22:56 AM: Restored the cached .next folder at the location `.next/cache`
9:22:56 AM: ​
9:22:56 AM: (netlify-plugin-cache-nextjs onPreBuild completed in 321ms)
```

**Comment by pmourer** [comment]
this line is interesting:
```
9:22:54 AM:    - netlify-plugin-cache-nextjs@1.5.0 from netlify.toml and package.json
```

**Comment by pmourer** [comment]
do you have this plugin in package.json locked at a specific version?

**Comment by pmourer** [comment]
moar PRs!!!!!!

**Comment by moop-moop** [comment]
> 
> 
> do you have this plugin in package.json locked at a specific version?

Yes, apparently the second repo/project I mentioned is installed with 1.5 and configured in the `netlify.toml`. It is ALSO configured to use the netlify.com configuration-less plugin. :man_facepalming:

Well I guess having both is not an issue....

**Comment by pizzafox** [comment]
Ok, I think I've figured it out.

Looking at the logs of someone who wanted to have their plugin added to Netlify's list I saw this line:

```
netlify-plugin-cache@1.0.1 from netlify.toml and package.json
```

Try adding the plugin as a devdependency to your project and Netlify should load that version.

**Comment by pmourer** [comment]
@pizzafox This still does not seem to have worked :/ 
```
1:25:28 PM: ┌─────────────────────────────┐
1:25:28 PM: │        Netlify Build        │
1:25:28 PM: └─────────────────────────────┘
1:25:28 PM: ​
1:25:28 PM: ❯ Version
1:25:28 PM:   @netlify/build 3.3.5
1:25:28 PM: ​
1:25:28 PM: ❯ Flags
1:25:28 PM:   deployId: 5f57da8b148a54151aaaebcc
1:25:28 PM:   mode: buildbot
1:25:28 PM: ​
1:25:28 PM: ❯ Current directory
1:25:28 PM:   /opt/build/repo
1:25:28 PM: ​
1:25:28 PM: ❯ Config file
1:25:28 PM:   /opt/build/repo/netlify.toml
1:25:28 PM: ​
1:25:28 PM: ❯ Context
1:25:28 PM:   deploy-preview
1:25:29 PM: ​
1:25:29 PM: ❯ Loading plugins
1:25:29 PM:    - netlify-plugin-cache-nextjs@1.5.0 from netlify.toml and package.json
1:25:30 PM: ​
1:25:30 PM: ┌────────────────────────────────────────────────────────┐
1:25:30 PM: │ 1. onPreBuild command from netlify-plugin-cache-nextjs │
1:25:30 PM: └────────────────────────────────────────────────────────┘
1:25:30 PM: ​
1:25:30 PM: .next/cache does not exist on disk
1:25:30 PM: Couldn't restore the cache for the .next folder at the location `.next/cache`
​
1:25:30 PM: (netlify-plugin-cache-nextjs onPreBuild completed in 249ms)
1:25:30 PM: ​
```
I did a single deploy (with the package added to package.json, confirmed it ran the onPostBuild correctly (or at least the output said that it cached successfully) and then selected "Retry Deploy"

**Comment by pmourer** [comment]
Is it possible that this caching will not work for deploy-previews?

**Comment by pmourer** [comment]
I noticed that all of @moop-moop 's deploys are production context

**Comment by pizzafox** [comment]
I truly have no idea why this is happening. It works on my site, we're all running the latest version of the plugin.

I'm going to try doing some random refactoring in the hopes it fixes it (it probably won't).

**Comment by pmourer** [comment]
@pizzafox it works under all contexts for you as well?

**Comment by pizzafox** [comment]
I am testing in a production context, deploy previews eat up my build minutes.

**Comment by pmourer** [comment]
hm ok, well i think that is certainly something that i would want to double check, as I have _only_ used deploy previews at this point

**Comment by moop-moop** [comment]
We have build minutes, I will check out various open PRs that use the plugin.

**Comment by moop-moop** [comment]
> 
> 
> We have build minutes, I will check out various open PRs that use the plugin.

Our deploy-previews are restoring the cache on both projects that use the plugin (one on version 1.4, the other 1.5).

**Comment by pmourer** [comment]
hmmm, thanks @moop-moop for checking anyhow.

**Comment by moop-moop** [comment]
When I was seeing what seems like the same unexplained issue late July, I had cases where simply commiting to the branch (used in the PR) caused the cache to be restored all of sudden. Almost like the specific commit itself was broken.

**Comment by moop-moop** [comment]
> 
> 
> When I was seeing what seems like the same unexplained issue late July, I had cases where simply commiting to the branch (used in the PR) caused the cache to be restored all of sudden. Almost like the specific commit itself was broken.

And creating a new commit resolved the block.

**Comment by pmourer** [comment]
oh hmm -- like maybe there needs to be a commit in the commit history that created a deploy with a cache, and then the next commit would cause a deploy that could reference that cache -- let me see if i can make that happen.

**Comment by pmourer** [comment]
doesn't seem to have done anything -- added a commit where i just added a newline to netlify.toml just for the sake of testing, the deploy of that commit also could not cache. The previous deploy on that deploy-preview for that branch ran the onPostBuild successfully (according to build logs).

**Comment by pizzafox** [comment]
If anyone could try giving a reproducible site that would be great. I'm not sure if this is a Next.js issue, a Netlify bug, or some weird behavior Netlify does.

**Comment by Michael-Reich** [comment]
Same problem, could not found a solution:

netlify.toml
```
[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"
[[plugins]]
  package = "netlify-plugin-cache-nextjs"
```

next.config.js
```
// next.config.js
const path = require('path')

module.exports = {
  // Target must be serverless
  target: 'serverless',
  sassOptions: {
    includePaths: [path.join(__dirname, 'styles')],
  },
};

```

package.json
```
{
  "name": "",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next-boost",
    "postbuild": "next-on-netlify",
    "lint": "eslint ./components/** ./pages/** -c .eslintrc.js --ext js,jsx",
    "lint-fix": "eslint ./components/** ./pages/** -c .eslintrc.js --fix --ext js,jsx"
  },
  "dependencies": {
    "@socialgouv/matomo-next": "^1.1.2",
    "axios": "^0.20.0",
    "bootstrap": "^4.5.3",
    "next": "9.5.5",
    "next-boost": "^0.7.7",
    "next-on-netlify": "^2.5.1",
    "react": "17.0.0",
    "react-awesome-slider": "^4.1.0",
    "react-bootstrap": "^1.4.0",
    "react-dom": "17.0.0",
    "react-lazyload": "^3.1.0",
    "react-shufflejs": "^0.2.0",
    "react-slick": "^0.27.12",
    "sass": "^1.27.0",
    "shufflejs": "^5.2.3",
    "slick-carousel": "^1.8.1",
    "storyblok-js-client": "^3.1.1",
    "storyblok-react": "^0.1.1"
  },
  "devDependencies": {
    "eslint": "^7.12.0",
    "eslint-plugin-react": "^7.21.5",
    "netlify-plugin-cache-nextjs": "^1.5.2"
  }
}
```

**Comment by oliviertassinari** [comment]
This is an issue with Netlify: https://github.com/netlify/build-image/issues/480.

**Comment by pizzafox** [comment]
> Is it possible that this caching will not work for deploy-previews?

@pmourer called it 2 months back.
I should have done a better job testing and have figured out specifically what was wrong. Glad that this is getting resolved soon.

**Comment by oliviertassinari** [comment]
I'm not sure it will be resolved soon. The issue has been stale for a long time, nor it seems to have received a lot of upvotes. On our side, this would save 5min of build. The large majority of our builds are previews.

**Comment by kaganjd** [comment]
👋🏻 found this issue linked to https://github.com/netlify/build-image/issues/480 - that issue should now be resolved thanks to change that rolled out on Tuesday to how we do Deploy Preview caching. Check out https://community.netlify.com/t/build-cache-is-now-updated-in-deploy-preview-builds/26344 for more details

**Comment by jorisw** [comment]
I'm still getting this, even after a "Retry" on my build:
> No cache found for the .next folder at the location `.next/cache`

I did a first deploy to generate the cache, then hit Retry Deploy to try and use it.



First deploy:

```
2:59:20 PM: ┌─────────────────────────────────────────────────────────┐
2:59:20 PM: │ 3. onPostBuild command from netlify-plugin-cache-nextjs │
2:59:20 PM: └─────────────────────────────────────────────────────────┘
2:59:20 PM: ​
2:59:20 PM: Cached the .next folder at the location `.next/cache`
2:59:20 PM: ​
2:59:20 PM: (netlify-plugin-cache-nextjs onPostBuild completed in 728ms)
```

Second deploy:

```
3:01:55 PM: ❯ Loading plugins
3:01:55 PM:    - netlify-plugin-cache-nextjs@1.4.0 from netlify.toml
3:01:56 PM: ​
3:01:56 PM: ┌────────────────────────────────────────────────────────┐
3:01:56 PM: │ 1. onPreBuild command from netlify-plugin-cache-nextjs │
3:01:56 PM: └────────────────────────────────────────────────────────┘
3:01:56 PM: ​
3:01:56 PM: No cache found for the .next folder at the location `.next/cache`
3:01:56 PM: ​
3:01:56 PM: (netlify-plugin-cache-nextjs onPreBuild completed in 191ms)
3:01:56 PM: ​
3:01:56 PM: ┌────────────────────────────────────┐
3:01:56 PM: │ 2. build.command from netlify.toml │
3:01:56 PM: └────────────────────────────────────┘
3:01:56 PM: ​
3:01:56 PM: $ yarn build && yarn export
3:01:57 PM: yarn run v1.17.0
3:01:57 PM: $ next build
3:01:58 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
```

**Comment by pizzafox** [comment]
Fix has been released for a week now, issue should be resolved.

**Comment by jorisw** [comment]
It is, but I did have to 'tickle' my build with an actual commit, rather than a Retry Deploy, for the cache written by the first deploy to be picked up by the second.
